### ISSUE TITLE
How to translate .po to .pbl?

### ISSUE THREAD

**Issue by icbrg** [MarSoft/pebble-firmware-utils#18]
I tried to translate it with translate.py but

> Traceback (most recent call last):
>   File "C:\Users\sergi\Desktop\pebble-firmware-utils-master\translate.py", line 556, in <module>
>     translate_fw(args)
>   File "C:\Users\sergi\Desktop\pebble-firmware-utils-master\translate.py", line 358, in translate_fw
>     print >>log, "WARNING: no usable ranges!"
> TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'

Website is down and your email inbox is full. Regards

**Comment by MarSoft** [comment]
Hello. Not sure about my inbox, because I successfully received notification about this GH issue.  Translate script is totally obsolete, it was intended for making baked-in translations, not language packs. What you need is lang pack generator (https://pebware.herokuapp.com/langs) which is currently working. Please follow up if you have some issues with it.
